import "@/styles/globals.css";
import SideBar from "components/SideBar";

export const metadata = {
  title: "ChatGPT Application",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex">
          <div className="bg-[#202123] max-w-xs 
          h-screen overflow-y-scroll md:min-w-[300px]">
            <SideBar />
          </div>
          <div className="bg-[#343541] flex-1">{children}</div>
        </div>
      </body>
    </html>
  );
}
